# Generated by Django 4.2.7 on 2023-11-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(max_length=5)),
                ('precio', models.IntegerField(max_length=10)),
                ('imagen', models.ImageField(upload_to='flores/')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(max_length=5)),
                ('total', models.IntegerField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_cliente', to='flores.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_producto', to='flores.producto')),
            ],
        ),
    ]
